version: "3.9"
services:
  react:
    build:
      context: ./ssafynity-f
      dockerfile: Dockerfile
    container_name: react
    ports:
      - "3000:80"
    networks:
      - ssafynity-network

  springboot:
    build:
      context: ./SSAFYnity_B
      dockerfile: Dockerfile
    container_name: springboot
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - ssafynity-network
    depends_on:
      - mysql
      - mongodb
      - elasticsearch

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - react
      - springboot
    networks:
      - ssafynity-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    networks:
      - ssafynity-network
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ssafynity
    volumes:
      - mysql_data:/var/lib/mysql

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - ssafynity-network
    volumes:
      - mongodb_data:/data/db

  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true       # 보안 활성화
      - ELASTIC_PASSWORD=elastic   # elastic 사용자 비밀번호 설정
    ports:
      - "9200:9200"
    networks:
      - ssafynity-network
    volumes:
      - es_data:/usr/share/elasticsearch/data

networks:
  ssafynity-network:
    driver: bridge

volumes:
  mongodb_data:
  es_data:
  mysql_data: